// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Seagregalastablasalabasededatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seagregalastablasalabasededatos));
        
        string IMigrationMetadata.Id
        {
            get { return "202404260059225_Se agrega las tablas a la base de datos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
